name: Unittest
on:
  push:
    branches:
    - master
    - release/**
    - feature/**
jobs:
  detect-changes:
    name: Detect Changes
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.filter.outputs.changes }}
    steps:
    - uses: actions/checkout@v4
      name: Check out code into directory
    - uses: dorny/paths-filter@v3
      name: Detect Module Changes
      id: filter
      with:
        filters: |
          bitget: ./bitget/**
          foobar: ./foobar/**
  unittest:
    name: Run Unittests
    runs-on: ubuntu
    needs: [detect-changes]
    continue-on-error: true
    if: ${{ needs.detect-changes.outputs.modules != '[]' }}
    strategy:
      fail-fast: false
      matrix:
        modules: ${{ fromJSON(needs.detect-changes.outputs.modules) }}
    steps:
    - uses: actions/checkout@v4
      name: Check out code into the Go module directory
    - uses: actions/setup-go@v5
      name: Set up Go 1.x
      with:
        go-version: ^1.22
    - working-directory: ${{ matrix.modules }}
      run: go test -v ./...
